# Generated by Django 3.2.5 on 2022-07-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='count',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tweets',
            options={'managed': True},
        ),
    ]
